### ISSUE TITLE
Files Not Generated On .NET Core

### ISSUE THREAD

**Issue by sirgru** [tunnelvisionlabs/antlr4cs#303] opened 2018-08-29 21:25 UTC
I can get the files generated properly on .NET Framework, but not .NET core. Here is my .csproj.

```
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Antlr4" Version="4.6.5-rc002" />
    <PackageReference Include="Antlr4.CodeGenerator" Version="4.6.5-rc002" />
    <PackageReference Include="Antlr4.Runtime" Version="4.6.5-rc002" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Grammar\TheLexer.g4">
      <Generator>MSBuild:Compile</Generator>
    </None>
    <None Update="Grammar\TheParser.g4">
      <Generator>MSBuild:Compile</Generator>
    </None>
  </ItemGroup>

</Project>
```

**Comment by sharwell** [comment] 2018-08-30 01:28
Duplicate of #296. This is pretty serious and I hope to make progress on it this week.

**Closed** 2018-08-30 01:28 UTC
Labels: duplicate
