### ISSUE TITLE
Encoding issues for foreign characters (utf8)

### ISSUE THREAD

**Issue by juergenr** [tunnelvisionlabs/antlr4cs#159] opened 2016-09-09 17:07 UTC
Environment: 
- Windows 10 (non english), 
- Visual Studio 15 (up-to-date, english) , 
- Antlr4cs 4.5.3 

Simple Grammar (saved as utf8):
```
grammar TestGrammar;
text:		WORD*;
WORD:		[a-zA-Z0-9?!#öäüÖÄÜß我"'-]+;	 
```
Code (saved as utf8):
```
var input = new AntlrInputStream("öäü我");

var lexer = new TestGrammarLexer(input);
var tokens = new CommonTokenStream(lexer);
var parser = new TestGrammarParser(tokens);
var tree = parser.text();
```

I get a "token recognition error" for each character. 
Normal ASCII input works fine.
I also tried `MemoryStream ms = new MemoryStream(Encoding.UTF8.GetBytes("awoäbd"));` as input without success.
The GitHub repository master 9/9/2016 does get the same errors.

I really like that library - thanks for your work!

**Comment by sharwell** [comment] 2016-09-09 20:54
I believe this is a duplicate of #135.

**Closed** 2016-09-09 20:56 UTC
Labels: duplicate
