### ISSUE TITLE
Undocumented Build process

### ISSUE THREAD

**Issue by ericschultz** [tunnelvisionlabs/antlr4cs#35] opened 2014-01-06 17:36 UTC
I'm not entirely clear how to build my own version of the NuGet packages to work around bugs. I think it involves running mvn but otherwise I'm unsure. Are there any sort of instructions?

**Comment by sharwell** [comment] 2017-01-14 21:09
I'm going to mark this as a duplicate of #109 since that one has newer information.

**Closed by sharwell** 2017-01-14 21:09 UTC
