### ISSUE TITLE
Problems with Antlr4 and Visual Studio 2017

### ISSUE THREAD

**Issue by awbushnell** [tunnelvisionlabs/antlr4cs#310] opened 2018-10-12 21:24 UTC
Hello, we are experiencing build issues in our CSProject when we build using the Visual Studio 2017 IDE.  Specifically, what is noticed is that the intermediate files generated by Antlr are getting cleaned but not regenerated during incremental builds? If we "touch" the grammar file, they come back and we get a successful build but next change to any other file again loses them...  Our csproj has the following in it, what are we missing? Do we need to update/upgrade to a newer version for 2017?

We reference the runtime: 

```xml
<Reference Include="Antlr4.Runtime, Version=4.6.0.0, Culture=neutral, PublicKeyToken=09abb75b9ed49849, processorArchitecture=MSIL">
  <HintPath>..\..\packages\Antlr4.Runtime.4.6.4\lib\net45\Antlr4.Runtime.dll</HintPath>
</Reference>
```

We setup the build:

```xml
<Antlr4 Include="Utility\ParamExprGrammar.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>Revit.IFC.Export.Utility</CustomToolNamespace>
      <Listener>True</Listener>
      <Visitor>True</Visitor>
</Antlr4>
```

we check for and import the necessary target files:

```xml
 <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.props')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.props'))" />
    <Error Condition="!Exists('$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.targets')" Text="$([System.String]::Format('$(ErrorText)', '$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.targets'))" />
  </Target>
  <Import Project="$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.targets" Condition="Exists('$(SolutionDir)packages\Antlr4.CodeGenerator.4.6.4\build\Antlr4.CodeGenerator.targets')" />
```

thanks.

**Comment by sharwell** [comment] 2018-10-12 21:37
This is a new one for me.

What version of Visual Studio 2017 are you using?

**Comment by awbushnell** [comment] 2018-10-12 21:38
I am on the latest, 15.8.7

**Comment by sharwell** [comment] 2018-10-12 21:40
Can you test the 4.6.6-rc001 release and let me know if the problem is resolved? If not, can you enable the new code generator with 4.6.6-rc001 as described in [these release notes](https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.5-beta001) and let me know if the problem is resolved?

**Comment by awbushnell** [comment] 2018-10-12 21:57
Ok, I updated to that release and now the issue seems to have gone away... At least the steps to replicate are no longer happening.. I will stay on this version and keep my eyes peeled and thanks!!!!!!!!

**Comment by sharwell** [comment] 2018-10-12 22:03
@awbushnell Thanks! I'm hoping to release that update as a stable patch release soon. I would recommend using the updated C# code generator since it's much faster than the old one.

**Comment by awbushnell** [comment] 2018-10-12 22:08
@sharwell Ok, I followed the steps to enable the C# generator.. will see how it goes.. thanks!

**Comment by awbushnell** [comment] 2018-10-22 14:37
@sharwell we are still experiencing issues with the Antlr' task/code generator and Visual Studio 2017... Do you have other users on that platform and have they been successful? Have you tried this?  I am finding flaky build behaviour where somewhat (seemingly) randomly the generated cs files go missing and the build fails. We have seen CLEAN builds fail etc. and am wondering if maybe we have a setup issue or are you aware of 2017 Build issues? I am pawing over log files now (Diagnostic build logs from Visual studio) to see if I can get a clue.. but figured I would reach out.

**Comment by awbushnell** [comment] 2018-10-22 15:11
@sharwell  I think I see what might be going on... The import of the targets files in project is conditional on the presence of the antlr target files.. So what I see going on (at least for me) is that the first time I open our Solution, the packages do not exist as it is on a clean system/build etc.. Then when I build, nuget packages get downloaded and the build proceeds.  However, what appears to be happening is that when our solution is loaded the csproj containing the Antlr4 targets import is loaded and the imports evaluated, since the package does not yet exist, the target file is not imported.. Now I start to build and we do download/install the nuget packages, however, the import statement is not reevaluated so the targets do not get imported and the cs files never generated... It seems if I close and reopen the solution that all is better...

**Comment by sharwell** [comment] 2018-10-27 06:02
@awbushnell Thanks for the update. This issue is resolved by the new `<PackageReference>` feature of NuGet. Users working with one of the old style imports will need to use the workaround you found (reload the solution after restoring packages).

**Closed** 2018-10-27 06:02 UTC
Labels: bug

**Comment by awbushnell** [comment] 2018-10-29 15:30
@sharwell Thank you for the confirmation. I will work on migrating our project to using PackageReferences, though an initial attempt did not work.. but it was a quick try and I need to see what happened..

**Comment by awbushnell** [comment] 2018-10-31 17:11
@sharwell I am sorry, but I am finding that even using PackageReferencing, that the build errors still exist the first time through a solution load when the packages have not been downloaded yet... this is very problematic for our developers. 


So the scenario we are facing, is you open our solution with the package references setup on a machine that has not downloaded the packages yet.. Now you open the solution and build in the IDE.. as part of the build the proper packages download, yet the code generation does not happen!!!  If you reload the project and build it is fine.. but not really ideal. 

I believe this is due to the fact that the "import" of the props and targets files are not allowed during PackageRestore... so we are still facing the chicken and egg issue. Have you NOT seen this?   FYI, we are on 15.8.8 of Visual Studio 2017.

**Comment by sharwell** [comment] 2018-10-31 17:47
I've seen a bunch of issues in the past related to the first-time package installation problem. For example, the project I currently work on for work won't even load in VS until a manual command-line restore operation is performed.

The part that confuses me is NuGet _should_ be restoring packages when you load your solution, and then reevaluating the projects. Here is the setting controlling this:

![image](https://user-images.githubusercontent.com/1408396/47807739-d81d2400-dd0a-11e8-8657-33e6c9fe0aee.png)

It's possible this operation is not automatic in the 'csproj' project system (the csproj project format that's existed for several releases now). If that's the case, a restore operation could be performed by right clicking the solution in **Solution Explorer** and selecting **Restore NuGet Packages**.

**Comment by awbushnell** [comment] 2018-10-31 18:12
@sharwell What I am seeing is that the packages are being restored during our build as I have the options checked that you see.. HOWEVER, what is NOT happening during this initial restore, is the import of the targets, so that reevaluation of the projects.. In fact, the wrapper props and targets files generated by the PackageReference explicitly has a check for if the package is being restored and does NOT do the import if that is the case.. I have posted on the Nuget/Package reference github this same issue... 

[Failed Import on initial restore](https://github.com/NuGet/Home/issues/7457)
