### ISSUE TITLE
Visual Studio 2015 Support

### ISSUE THREAD

**Issue by nikeee** [tunnelvisionlabs/antlr4cs#132] opened 2016-01-29 02:30 UTC
The ANTLR Language Support Extension as listed here:
https://visualstudiogallery.msdn.microsoft.com/25b991db-befd-441b-b23b-bb5f8d07ee9f
Is listed as not compatible with VS 2015 and therefore cannot be used with VS >= 2015.

I'd love to have support for this extension in VS2015.

**Comment by midiway** [comment] 2016-05-09 13:50
plz, take a look at https://visualstudiogallery.msdn.microsoft.com/836c87a4-b182-4899-b014-ae40f4e32b4b

**Comment by nikeee** [comment] 2016-05-18 11:16
I downloaded the VSIX of antlr4cs of the store and unpacked it. In it, there is an xml file containing a list of supported VS versions. When I add VS2015 to the list and pack it again, it installs flawlessly and seems to work, too.
So maybe there is no migration work to do, just update the manifest.

**Comment by sharwell** [comment] 2016-06-17 03:34
Duplicate of tunnelvisionlabs/LangSvcV2#63 (where the ANTLR extension's code is located).

We're still limited by a major bug which was introduced in Visual Studio 2015, where it refuses to load some of our dependencies.

**Closed by sharwell** 2016-06-17 03:34 UTC
