### ISSUE TITLE
Task Antlr4ClassGenerationTask fails in mono 4.6.2 (XBuild 14.0)

### ISSUE THREAD

**Issue by MaximTrushin** [tunnelvisionlabs/antlr4cs#172] opened 2017-01-09 22:53 UTC
The task fails with the message "Unknown build error":

_Unknown build error: Executing command: "C:\Program Files (x86)\Java\jre1.8.0_111\bin\java.exe" -cp C:\_projects\MalinaNew\src\Malina.Antlr\packages\Antlr4.4.5.3\build\..\tools\antlr4-csharp-4.5.3-complete.jar org.antlr.v4.CSharpTool -o obj\Debug\ -no-listener -no-visitor -package Malina.Parser C:\_projects\MalinaNew\src\Malina.Antlr\MalinaLexer.g4_

Everything works fine if I execute the above command in cmd.
The full build log is attached.

**Comment by MaximTrushin** [comment] 2017-01-24 16:48
Thank you for looking into this issue! I really appreciate your work on this project.

**Comment by sharwell** [comment] 2017-07-06 19:17
Duplicate of #200

**Closed by sharwell** 2017-07-06 19:17 UTC
Labels: enhancement, up for grabs
