### ISSUE TITLE
CLSCompliant attribute causes compiler warnings in VS2019

### ISSUE THREAD

**Issue by garyhuntddn** [tunnelvisionlabs/antlr4cs#347] opened 2020-05-23 13:15 UTC
I prefer the scenario where the compiler has no need to generate warnings/information messages.

I've implemented a PR that allows the use of CLSCompliant<false> to be dictated by the build task for scenarios where the project isn't expecting to be CLS compliant.

It's probably just me being picky but if you're interested in including the PR then by all means do so.

**Comment by sharwell** [comment] 2020-12-29 17:17
Duplicate of #10

**Comment by sharwell** [comment] 2020-12-29 17:18
See https://github.com/tunnelvisionlabs/antlr4cs/issues/10#issuecomment-66999851 for the expected resolution to this. Not only will marking your assembly `CLSCompliant(false)` fix the warnings, but it will also make the compiler faster.

**Closed by sharwell** 2020-12-29 17:17 UTC
