### ISSUE TITLE
extraction of literals

### ISSUE THREAD

**Issue by widc** [tunnelvisionlabs/antlr4cs#145] opened 2016-07-13 10:31 UTC
Not all literals located in the .g4 file are found by the following chunk of code. Lines similar to "OfEach: 'of each' | 'for each';" (capital initial letter + alternatives separated by the pipe symbol) yield nulls instead of the literals:

```csharp
            // read in literals from the grammar
            Type type = typeof(SRFCLexer);
            System.Reflection.BindingFlags bindingAttr = System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Static;
            System.Reflection.FieldInfo info = type.GetField("_LiteralNames", bindingAttr);
            object value = info.GetValue(null);
            literals = (string[])value;
            // Some literals are not included in literals, specifically those which are found as _alternatives_ for a token, e.g. "Set:		'set'|'Set';" (the pipe "|" is important here).

**Comment by sharwell** [comment] 2016-07-15 13:13
This is by design. A literal name is only assigned to a token in cases where the token only matches one specific literal. Any deviation from this, including the use of `*`, `+`, `?`, `|`, or references to other rules, means the token is no longer considered a literal and is only assigned its symbolic name (which is the name of the lexer rule defining it).

> :bulb: It looks like you are using reflection to access a field which is exposed by [`IVocabulary.GetLiteralName`](https://github.com/tunnelvisionlabs/antlr4cs/blob/master/runtime/CSharp/Antlr4.Runtime/IVocabulary.cs#L83).

**Comment by sharwell** [comment] 2016-07-15 13:15
I'm going to close this issue only because the current design is taken directly from the behavior of the reference release of ANTLR 4 (Java). To incorporate a change in behavior for literals, the change would first need to be incorporated in the Java code by filing an [issue here](https://github.com/antlr/antlr4/issues), and then it would come to the C# port.

**Closed by sharwell** 2016-07-15 13:15 UTC

**Comment by widc** [comment] 2016-07-16 06:51
Thanks a lot for your advice.
