### ISSUE TITLE
Can not build project with vs2017

### ISSUE THREAD

**Issue by ryanlin1986** [tunnelvisionlabs/antlr4cs#190] opened 2017-03-09 02:07 UTC
After upgraded to vs2017, the following error occurs when building:
Rebuild All started ...
  
  Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
     --- End of inner exception stack trace ---
     at Antlr4.Build.Tasks.AntlrClassGenerationTaskInternal.HandleOutputDataReceived(Object sender, DataReceivedEventArgs e)
     at System.Diagnostics.Process.OutputReadNotifyUser(String data)
     at System.Diagnostics.AsyncStreamReader.FlushMessageQueue()
     at System.Diagnostics.AsyncStreamReader.GetLinesFromStringBuilder()
     at System.Diagnostics.AsyncStreamReader.ReadBuffer(IAsyncResult ar)
     at System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(Object completedTask)
     at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
     at System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(Task completingTask)
     at System.Threading.Tasks.Task.FinishContinuations()
     at System.Threading.Tasks.Task.FinishStageThree()
     at System.Threading.Tasks.Task.FinishStageTwo()
     at System.Threading.Tasks.Task.Finish(Boolean bUserDelegateExecuted)
     at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
     at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
     at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
     at System.Threading.ThreadPoolWorkQueue.Dispatch()
     at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
========== Rebuild All: 0 succeeded, 1 failed, 0 skipped ==========

**Comment by sharwell** [comment] 2017-03-09 02:28
This is a duplicate of #173. I released a beta with initial support (4.6.1-beta001), but it has a couple minor bugs that I'm fixing tonight for a beta002.

**Closed by sharwell** 2017-03-09 02:28 UTC

**Comment by ryanlin1986** [comment] 2017-03-10 08:56
Thanks for the help;)
