### ISSUE TITLE
Warning CS3021 Potiential Fix

### ISSUE THREAD

**Issue by zombiepigdragon** [tunnelvisionlabs/antlr4cs#330] opened 2019-05-31 23:18 UTC
There's the common issue in this in which Warning CS3021: "... does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute" appears. While it's possible to disable it for the assembly, isn't it also possible to simply add 2 lines into the code generator to automatically disable it? I am incapable of building ANTLR from scratch for a few reasons, but it seems like adding 
```
// Does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute
#pragma warning disable 3021
```
to `/antlr4cs/tool/resources/org/antlr/v4/tool/templates/codegen/CSharp/CSharp.stg` would be able to fix the issue of the warning displaying without issues. Is that a valid solution, or do I just have to do it the old-fashioned way?

**Comment by sharwell** [comment] 2019-06-04 10:32
You just need to mark your assembly with `CLSCompliant(false)`. As a bonus (in addition to addressing this warning), the compiler will be slightly faster.

**Comment by sharwell** [comment] 2019-06-04 11:05
Duplicate of #10

**Closed by sharwell** 2019-06-04 11:05 UTC
