### ISSUE TITLE
No encoding settings.

### ISSUE THREAD

**Issue by GeneralGDA** [tunnelvisionlabs/antlr4cs#157] opened 2016-09-09 03:44 UTC
I've got an unusual setup: grammar file (*.g4) and DSL files with non-English character (Russian letters, actually). Also, the default encoding on my PC is windows-1251. So the problem is that there is no way to setup grammar file encoding and output parser file encoding for ANTRL bundled with the NuGet package. Exact case is next: 

1. g4 file is in UTF-8, DSL files are in UTF-8
2. I compile and run the project: parsing fails.
3. I convert g4 file and DSL files into windows-1251 - all is OK.

There are no such problems with naked ANTLR: both flavors of it (TestRig and parser generator) accept input file encoding as a command-line argument.

**Comment by sharwell** [comment] 2016-09-09 07:50
This is probably a duplicate of #135. I have a pull request up to fix it (#146); would you like to check it out and provide feedback on it?

**Closed** 2016-09-09 07:51 UTC
Labels: duplicate

**Comment by GeneralGDA** [comment] 2016-09-09 07:53
Seems like you are rigth. What do I need to do, to check if the pull reqest fixes the problem?

**Comment by sharwell** [comment] 2016-09-09 08:04
I tried to rebuild the pull request (which would post a fresh copy of the build artifacts for you), but it seems to be broken on a dependency right now. It's late so I'll have to look back at this tomorrow.
