### ISSUE TITLE
Disable warning 3021 (CLSCompliant Attribute)

### ISSUE THREAD

**Issue by c272** [tunnelvisionlabs/antlr4cs#333] opened 2019-07-06 13:56 UTC
On my combined grammar generated code, there are `pragma` statements to disable other common useless warnings such as these:

```
// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419
```

Could warning `3021` also be disabled ('grammarName' does not need a CLSCompliant attribute because the assembly does not have a CLSCompliant attribute), as it is a useless warning, similar to the above. 

See [here](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs3021) for the Microsoft page on the warning.

**Comment by sharwell** [comment] 2019-07-11 14:15
Duplicate of #10

**Comment by sharwell** [comment] 2019-07-11 14:15
See https://github.com/tunnelvisionlabs/antlr4cs/issues/10#issuecomment-66999851 for the recommended solution 😄

**Closed** 2019-07-11 14:16 UTC
Labels: duplicate
