### ISSUE TITLE
event EnterCaseCondExprValue don't fire

### ISSUE THREAD

**Issue by lsalamon** [tunnelvisionlabs/antlr4cs#259] opened 2017-11-21 00:47 UTC
<b>For exact lines:</b>
<pre>
Dim grade As String
Private Sub Compute_Click( )
grade=txtgrade.Text
Select Case grade
Case "A"
result.Caption="High Distinction"
Case "A-"
result.Caption="Distinction"
Case "B"
result.Caption="Credit"
Case "C"
result.Caption="Pass"
Case Else
result.Caption="Fail"
End Select
End Sub
</pre>
<b>Event EnterCaseCondExprValue don't fire but fire event ExitCaseCondExprValue.</b>
<b>Same code don't fire event EnterCaseCondExpr but fire ExitCaseCondExpr</b>
<b>Same code don't fire event EnterCaseCondElse but fire ExitCaseCondElse</b>

My env:
Antlr4 {4.6.4} VisualBasic6
Antlr4.CodeGenerator {4.6.4} VisualBasic6
Antlr4.Runtime {4.6.4} VisualBasic6

Visual Studio 2017 Community 15.4.4
Windows 10 (1709)

**Comment by retailcoder** [comment] 2017-11-21 02:21
I haven't worked on this repository, but I own a project that uses Antlr4, and it just so happens to be a project that parses and analyzes VBA (and soon VB6 in the VB6 IDE too) code.

Ref. #255, #256, #257 and #258. Exactly what grammar are you using? FYI [Rubberduck](https://github.com/rubberduck-vba/Rubberduck) v1.2, 1.3 and 1.4 were using a very similar to the VisualBasic6 grammar in the Antlr4 grammars repository; the enhanced grammar (intended for VBA but probably more than just fine for VB6) was contributed back under [VBA.g4](https://github.com/antlr/grammars-v4/blob/master/vba/vba.g4), because it supported a number of VBA-specific changes - but the enhancements include numerous bugfixes that improve the grammar in general.

...but that was all done with Antlr4.3. Now Rubberduck uses a grammar that was essentially rewritten entirely, against the official language specifications, and the project needs help upgrading it to the latest Antlr4, since our grammar somehow doesn't build in 4.6/4.7.

Feel free to study our work; I can't even begin to count the number of grammar issues we've encountered and fixed over the years. [This gives an idea](https://github.com/rubberduck-vba/Rubberduck/issues?q=is%3Aissue+is%3Aclosed+label%3Aantlr), perhaps. I'll be happy to merge a PR on Rubberduck that makes our grammars build on the latest Antlr4 - yeah, *grammars*, plural: if you're going to want to analyze VB6/VBA code, you're going to need to perform some kind of preprocessing - consider this:

```vb
#Const FOOBAR = True
#If FOOBAR Then
Dim foo As Class1
#Else
Dim foo As Class2
#End If
```

You'll want to know where & how `Foo` is declared, so you'll want to know which of these two branches is the "live" code, so you can tell whether `foo.DoSomething` is defined on `Class1`, `Class2`, or both: we have a grammar dedicated to this precompiler directives evaluation step - the original grammar couldn't handle that. IIRC it also failed to parse a `Const#` statement...

Does your parse tree contain error nodes? I'm pretty sure we dealt with a number of grammar problems involving `Select...Case` statements, too. Point is, if it's a grammar problem, it's not an Antlr problem.

**Comment by lsalamon** [comment] 2017-11-21 10:10
Hi, i just using VB6.G4 from (https://github.com/antlr/grammars-v4/tree/master/vb6)

The simple code below has error reported:

<b>For exact lines:</b>
<pre>
Dim grade As String
Private Sub Compute_Click( )
grade=txtgrade.Text
Select Case grade
Case "A"
result.Caption="High Distinction"
Case "A-"
result.Caption="Distinction"
Case "B"
result.Caption="Credit"
Case "C"
result.Caption="Pass"
Case Else
result.Caption="Fail"
End Select
End Sub
</pre>
<b>Event EnterCaseCondExprValue don't fire but fire event ExitCaseCondExprValue.</b>
<b>Same code don't fire event EnterCaseCondExpr but fire ExitCaseCondExpr</b>
<b>Same code don't fire event EnterCaseCondElse but fire ExitCaseCondElse</b>

**Comment by retailcoder** [comment] 2017-11-21 12:48
You sound like a broken record. I've read what you posted above and in the 4 identical previous issues. Posting more of the same isn't going to help identify what the problem is. What is the error? Does the parse tree have error nodes? In any case please stop spamming this repository with these "errors", first because this is the Antlr4 C# target repository, so issues are for the C# parser generator, not for specific grammar problems. Second, because you are not providing the helpful information that is being requested for clarification. "Has error reported" is useless without the actual error that's reported. Then again, this issue belongs on the grammar's repository, not here.

**Comment by sharwell** [comment] 2017-11-21 13:46
@lsalamon I reopened just this one issue for continued discussion.

Can you post an example of the code where you created an instance of `VisualBasic6Parser` and ran the listener which resulted in the observed problems?

**Comment by lsalamon** [comment] 2017-11-21 23:29
Code to simulate issue:
<pre>
using Antlr4.Runtime;
using Antlr4.Runtime.Misc;
using System;
using System.Text;
using VisualBasic6;

namespace VB6Parser
{
    internal class EvalVisitor : VisualBasic6BaseListener
    {
        public override void EnterCaseCondExprValue([NotNull] VisualBasic6Parser.CaseCondExprValueContext context)
        {
            Console.WriteLine("Hit EnterCaseCondExprValue!");
        }

        public override void ExitCaseCondExprValue([NotNull] VisualBasic6Parser.CaseCondExprValueContext context)
        {
            Console.WriteLine("Hit ExitCaseCondExprValue!");
        }

        public override void EnterCaseCondExpr([NotNull] VisualBasic6Parser.CaseCondExprContext context)
        {
            Console.WriteLine("Hit EnterCaseCondExpr!");
        }

        public override void ExitCaseCondExpr([NotNull] VisualBasic6Parser.CaseCondExprContext context)
        {
            Console.WriteLine("Hit ExitCaseCondExpr!");
        }

        public override void EnterCaseCondElse([NotNull] VisualBasic6Parser.CaseCondElseContext context)
        {
            Console.WriteLine("Hit EnterCaseCondElse!");
        }

        public override void ExitCaseCondElse([NotNull] VisualBasic6Parser.CaseCondElseContext context)
        {
            Console.WriteLine("Hit ExitCaseCondElse!");
        }
    }

    class Program
    {
        static void Main(string[] args)
        {
            StringBuilder sb = new StringBuilder();

            sb.AppendLine("Dim grade As String");
            sb.AppendLine("Private Sub Compute_Click()");
            sb.AppendLine("grade = txtgrade.Text");
            sb.AppendLine("Select Case grade");
            sb.AppendLine("Case \"A\"");
            sb.AppendLine("result.Caption = \"High Distinction\"");
            sb.AppendLine("Case \"A - \"");
            sb.AppendLine("result.Caption = \"Distinction\"");
            sb.AppendLine("Case \"B\"");
            sb.AppendLine("result.Caption = \"Credit\"");
            sb.AppendLine("Case \"C\"");
            sb.AppendLine("result.Caption = \"Pass\"");
            sb.AppendLine("Case Else");
            sb.AppendLine("result.Caption = \"Fail\"");
            sb.AppendLine("End Select");
            sb.AppendLine("End Sub");

            string inputFile = sb.ToString();

            var input = new AntlrInputStream(inputFile);
            var lexer = new VisualBasic6Lexer(input);
            var tokens = new CommonTokenStream(lexer);
            var parser = new VisualBasic6Parser(tokens);

            EvalVisitor ev = new EvalVisitor();

            parser.AddParseListener(ev);

            var tree = parser.startRule();

            Console.Write("Test finalized.");
            var name = Console.ReadLine();
        }
    }
}
</pre>

**Comment by retailcoder** [comment] 2017-11-22 02:14
Ok, so... I have a repro for the issue at hand, a fix for @lsalamon's code, and maybe also a bug for @sharwell 😄

It appears a listener attached to a parser effectively doesn't invoke its `EnterSomeSpecificRule` virtual methods (they're not *events*, you `override` them)... however `EnterEveryRule` *is* invoked, and you could use it as a work-around to capture entering context types - this is the output I get for it:

```none
Hit EnterStartRuleContext
Hit EnterModuleContext
Hit EnterModuleBodyContext
Hit EnterModuleBodyElementContext
Hit EnterModuleBlockContext
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterVariableStmtContext
Hit EnterVariableListStmtContext
Hit EnterVariableSubStmtContext
Hit EnterAmbiguousIdentifierContext
Hit EnterAsTypeClauseContext
Hit EnterTypeContext
Hit EnterBaseTypeContext
Hit EnterModuleBodyElementContext
Hit EnterSubStmtContext
Hit EnterVisibilityContext
Hit EnterAmbiguousIdentifierContext
Hit EnterArgListContext
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterAmbiguousKeywordContext
Hit EnterBlockStmtContext
Hit EnterSelectCaseStmtContext
Hit EnterValueStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterSC_CaseContext
Hit EnterSC_CondContext
Hit EnterSC_CondExprContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit EnterSC_CaseContext
Hit EnterSC_CondContext
Hit EnterSC_CondExprContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit EnterSC_CaseContext
Hit EnterSC_CondContext
Hit EnterSC_CondExprContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit EnterSC_CaseContext
Hit EnterSC_CondContext
Hit EnterSC_CondExprContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
Hit EnterSC_CaseContext
Hit EnterSC_CondContext
Hit ExitCaseCondElse!
Hit EnterBlockContext
Hit EnterBlockStmtContext
Hit EnterLetStmtContext
Hit EnterImplicitCallStmt_InStmtContext
Hit EnterICS_S_MembersCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterICS_S_MemberCallContext
Hit EnterICS_S_VariableOrProcedureCallContext
Hit EnterAmbiguousIdentifierContext
Hit EnterValueStmtContext
Hit EnterLiteralContext
```

However if I comment-out that override:

```csharp
    internal class EvalVisitor : VisualBasic6BaseListener
    {
        //public override void EnterEveryRule(ParserRuleContext context)
        //{
        //    Debug.WriteLine("Hit Enter" + context.GetType().Name);
        //}
```

...then I get the OP's output:

```none
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit ExitCaseCondElse!
```

...which from an API standpoint, is reasonably *unexpected*.

By walking the parse tree *after it's parsed*, using a `ParseTreeWalker`, I get the expected output:

```csharp
var input = new AntlrInputStream(code);
var lexer = new VisualBasic6Lexer(input);
var tokens = new CommonTokenStream(lexer);
var parser = new VisualBasic6Parser(tokens);

var tree = parser.startRule();

var visitor = new EvalVisitor();
var walker = ParseTreeWalker.Default;
walker.Walk(visitor, tree);
```

Output:

```none
Hit EnterCaseCondExpr!
Hit EnterCaseCondExprValue!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterCaseCondExpr!
Hit EnterCaseCondExprValue!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterCaseCondExpr!
Hit EnterCaseCondExprValue!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterCaseCondExpr!
Hit EnterCaseCondExprValue!
Hit ExitCaseCondExprValue!
Hit ExitCaseCondExpr!
Hit EnterCaseCondElse!
Hit ExitCaseCondElse!
```

I'm not sure *why* the overrides don't run when the listener is attached to the initial parse pass itself, given `EnterEveryRule` does. Could be a bug, could be a feature...

**Comment by retailcoder** [comment] 2017-11-22 02:41
Looking at Rubberduck's `VBAModuleParser` code:

```
var parser = new VBAParser(moduleTokens);
parser.AddErrorListener(errorListener);
ParserRuleContext tree;
try
{
    parser.Interpreter.PredictionMode = PredictionMode.Sll;
    tree = parser.startRule();
}
catch (ParsePassSyntaxErrorException syntaxErrorException)
{
   ...
}
...
foreach (var listener in listeners)
{
    ParseTreeWalker.Default.Walk(listener, tree);
}
```
<sub>https://github.com/rubberduck-vba/Rubberduck/blob/next/Rubberduck.Parsing/VBA/VBAModuleParser.cs#L48-L51</sub>

...seems we're avoiding during-parse listeners other than `IAntlrErrorListener<IToken>` during this critical phase, and using a `ParseTreeWalker` to walk the parse tree after it's completely parsed. #FoodForThought

**Comment by sharwell** [comment] 2017-11-22 03:31
I had a feeling `AddParseListener` was involved. This is the documented behavior of the method:

> ...
>
> To support output-preserving grammar transformations (including but not limited to left-recursion removal, automated left-factoring, and optimized code generation), calls to listener methods during the parse may differ substantially from calls made by `ParseTreeWalker.Default` used after the parse is complete. In particular, rule entry and exit events may occur in a different order during the parse than after the parser. In addition, calls to certain rule entry methods may be omitted.
>
> ...

https://github.com/tunnelvisionlabs/antlr4cs/blob/0b6de8686c26ce6f6ab9d11a3688873d6a513cf8/runtime/CSharp/Antlr4.Runtime/Parser.cs#L419-L451

**Comment by sharwell** [comment] 2017-11-22 03:32
Closing as **by design**.

**Closed** 2017-11-22 03:32 UTC
