### ISSUE TITLE
Build Error for .NET Core 2 using Visual Studio for Mac

### ISSUE THREAD

**Issue by cjlotz** [tunnelvisionlabs/antlr4cs#244] opened 2017-08-15 05:12 UTC
Hi

I've just updated all the tooling on the Mac to the latest .NET Core 2 bits released yesterday.  On Windows everything compiles successfully.  On Mac, when compiling from the command line using MSBuild everything seems to work, however when compiling from within VS for Mac, I get the following error:

`Target Antlr4Compile:
    Executing command: "/Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/../tools/ikvm.exe" -cp /Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/../tools/antlr4-csharp-4.6.5-SNAPSHOT-complete.jar org.antlr.v4.CSharpTool -o obj/Debug/netstandard2.0/ -encoding UTF-8 -no-listener -visitor -Dlanguage=CSharp -package Pragma.OnKey.RuleEngine /Users/carell/Documents/PragmaDev/onkey-plus-server/src/Pragma.OnKey.Infrastructure/RuleEngine/Rule.g4
    /Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Exception in thread "main" cli.System.NotSupportedException: The invoked member is not supported in a dynamic module.
    /Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: 	at cli.System.Reflection.Emit.TypeBuilder.check_created(Unknown Source)
    /Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: 	at cli.System.Reflection.Emit.TypeBuilder.RuntimeResolve(Unknown Source)
    /Users/carell/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: 	at cli.System.Reflection.Emit.ModuleBuilder.RuntimeResolve(Unknown Source)`

Looking at the error messages it seems strange that the command line build works though as it seems like some members are not available for compilation in .NET Core 2.  Any thoughts?

**Comment by sharwell** [comment] 2017-08-15 05:18
This is a duplicate of #243. I'm working on a long term solution which I plan to have available in about 3 weeks.

**Closed by sharwell** 2017-08-15 05:18 UTC

**Comment by rmsutton** [comment] 2017-11-14 02:13
Having the same issue. Any plans to fix this?

**Comment by lextm** [comment] 2017-12-15 05:10
@rmsutton Set `<Antlr4JavaExecutable>` in your project to the `java` location (use `whereis java` to locate that).

**Comment by rmsutton** [comment] 2018-03-03 22:58
@lextm That fixed my issue. Thank you!

Is there any way to have this picked up by default?
