### ISSUE TITLE
Visual Studio 2019 Support

### ISSUE THREAD

**Issue by Arkensor** [tunnelvisionlabs/antlr4cs#353] opened 2020-07-29 09:31 UTC
Hello there,

unfortunately, the support extensions [listed ](https://marketplace.visualstudio.com/items?itemName=SamHarwell.ANTLRLanguageSupport) on the readme is not updated to allow installation for VS2019.

I have edited the extension configs so you can install the package with the latest version of VS2019 and possibly also later versions: [Tvl.VisualStudio.Language.Antlr3.zip](https://github.com/tunnelvisionlabs/antlr4cs/files/4993864/Tvl.VisualStudio.Language.Antlr3.zip)

When using this version Visual Studio will block the loading unless you allow [synchronous autoload](https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/)

It would be really cool if the extension would get updated on the extension store so you can download it from the official mirror directly.

**Comment by kevinj2016** [comment] 2020-07-30 13:25
Hi, thank you for posting your modification. I tried to install the default one on VS2019 just now and it failed. I see Antlr3 in your zip filename - will your modification work with Antlr4? Thank you

**Comment by Arkensor** [comment] 2020-08-02 10:19
Hey @kevinj2016,

the filename is given by the package name of the original upload which was for antlr3. I am personally using it with antlr4 without any issues. It should be as easy as downloading the zip, extracting the enclosed vsix extension and double-clicking that.

**Comment by kevinj2016** [comment] 2020-08-02 15:15
@Arkensor , Thank you for your response. Unfortunately, the reason I posted was that the Antrl3.zip file failed to load into VS2019 the first time (even though I had the synchronous autoload option enabled). As you suggested above, I unzipped the file and double clicked it to load it, but received the following log messaqge.

2020-08-02 8:07:33 AM - Microsoft VSIX Installer
2020-08-02 8:07:33 AM - -------------------------------------------
2020-08-02 8:07:33 AM - vsixinstaller.exe version:
2020-08-02 8:07:33 AM - 16.6.2051
2020-08-02 8:07:33 AM - -------------------------------------------
2020-08-02 8:07:33 AM - Command line parameters:
2020-08-02 8:07:33 AM - C:\program files (x86)\microsoft visual studio\installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\ufo-dev\Projects Dev\0 Documentation\Tvl.VisualStudio.Language.Antlr3.vsix
2020-08-02 8:07:33 AM - -------------------------------------------
2020-08-02 8:07:33 AM - Microsoft VSIX Installer
2020-08-02 8:07:33 AM - -------------------------------------------
2020-08-02 8:07:33 AM - Initializing Install...
2020-08-02 8:07:33 AM - Extension Details...
2020-08-02 8:07:33 AM - 	Identifier         : Tvl.VisualStudio.Language.Antlr3.74dda0ee-262e-4c58-8255-d57136664d2b
2020-08-02 8:07:33 AM - 	Name               : ANTLR Language Support
2020-08-02 8:07:33 AM - 	Author             : Sam Harwell
2020-08-02 8:07:33 AM - 	Version            : 1.4.0
2020-08-02 8:07:33 AM - 	Description        : Basic support for the ANTLR grammar description language (V3 and V4).
2020-08-02 8:07:33 AM - 	Locale             : en-US
2020-08-02 8:07:33 AM - 	MoreInfoURL        : https://github.com/tunnelvisionlabs/LangSvcV2
2020-08-02 8:07:33 AM - 	InstalledByMSI     : False
2020-08-02 8:07:33 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - 	SignatureState     : Unsigned
2020-08-02 8:07:33 AM - 	Supported Products : 
2020-08-02 8:07:33 AM - 		Microsoft.VisualStudio.Community
2020-08-02 8:07:33 AM - 			Version : [11.0,16.0)
2020-08-02 8:07:33 AM - 		Microsoft.VisualStudio.Pro
2020-08-02 8:07:33 AM - 			Version : [11.0,16.0)
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - 	References         : 
2020-08-02 8:07:33 AM - 		-------------------------------------------------------
2020-08-02 8:07:33 AM - 		Identifier   : Tvl.VisualStudio.OutputWindow.3EF11167-A319-43DB-B1B4-A9778A90FAE0
2020-08-02 8:07:33 AM - 		Name         : Visual Studio Output Window Services
2020-08-02 8:07:33 AM - 		Version      : [3.0.0,)
2020-08-02 8:07:33 AM - 		MoreInfoURL  : 
2020-08-02 8:07:33 AM - 		Nested       : Yes
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - 		-------------------------------------------------------
2020-08-02 8:07:33 AM - 		Identifier   : Tvl.VisualStudio.Framework.922dc49e-a1f8-43c2-a748-504c676ebbb6
2020-08-02 8:07:33 AM - 		Name         : Visual Studio Extensibility Framework
2020-08-02 8:07:33 AM - 		Version      : [1.4.0,)
2020-08-02 8:07:33 AM - 		MoreInfoURL  : 
2020-08-02 8:07:33 AM - 		Nested       : Yes
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - 	Prerequisites      : 
2020-08-02 8:07:33 AM - 		-------------------------------------------------------
2020-08-02 8:07:33 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
2020-08-02 8:07:33 AM - 		Name         : Visual Studio core editor
2020-08-02 8:07:33 AM - 		Version      : [15.0,16.0)
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - Signature Details...
2020-08-02 8:07:33 AM - 	Extension is not signed.
2020-08-02 8:07:33 AM - 
2020-08-02 8:07:33 AM - Searching for applicable products...
2020-08-02 8:07:33 AM - **Found installed product - Global Location
2020-08-02 8:07:33 AM - Found installed product - Visual Studio Community 2019
2020-08-02 8:07:33 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.**
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)

**Comment by Arkensor** [comment] 2020-08-03 11:36
What kind of visual studio do you have? 

`    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Community" />
    <InstallationTarget Version="[11.0,17.0)" Id="Microsoft.VisualStudio.Pro" />`

Those are the supported ones

**Comment by kevinj2016** [comment] 2020-08-03 14:06
Hi,

Thank you for your continued help.

I just run the free visual studio community version, and program in C#.
I have done nothing special at all with it. (Except install the Resharper extension.)

Cheers, Kevin


[cid:image001.png@01D66964.A5ACF530]

**Comment by kevinj2016** [comment] 2020-08-03 14:07
Hi,

I don’t know if it matters, but I live in Canada. Maybe there’s a Canadian version?

Thank you
Kevin

**Comment by Arkensor** [comment] 2020-08-14 11:42
I have no idea. I ran it on other pcs as well that have VS 2019 installed. Why it is not working for you goes beyond my knowledge.

**Comment by swidz** [comment] 2020-09-10 11:33
I use MS Visual Studio 2019 Professional (lastest version 16.7.3 )
The installation was successful but after running VS I got the gold bar with the following message:

**Visual Studio did not load one or more extensions that were using deprecated APIs**

 I clicked on the "manage performance" link. I see that
**AntlrLanguagePackage** listed in Deprecated APIs with a note: This extension was not loaded because it uses deprecated synchronous autoload APIs.

You can find more info here: https://devblogs.microsoft.com/visualstudio/updates-to-synchronous-autoload-of-extensions-in-visual-studio-2019/ 

In order to run this extension it is necessary to allow synchronous autoload of extensions as described in the article but it has some influence on performance

Regards,
Sebastian

**Comment by lextm** [comment] 2020-09-11 02:53
@swidz That belongs to another repo https://github.com/kaby76/AntlrVSIX/issues

**Comment by swidz** [comment] 2020-09-11 04:55
@lextm AntlrVSIX works fine in VS2019. I meant the [https://github.com/tunnelvisionlabs/antlr4cs/files/4993864/Tvl.VisualStudio.Language.Antlr3.zip](Tvl.VisualStudio.Language.Antlr3.zip) file linked in the first post in this issue.

**Comment by lextm** [comment] 2020-09-11 20:45
@swidz then that's covered by https://github.com/tunnelvisionlabs/LangSvcV2/issues

**Comment by Skinz3** [comment] 2020-10-16 11:59
Please checkout : 
https://github.com/Skinz3/Antlr.CSharpTool

**Comment by kevinj2016** [comment] 2020-10-16 14:01
This looks like a wonderful tool.

Thank you!

**Comment by bpierson** [comment] 2020-12-11 06:56
@Arkensor, thank you for this! It works great. I had tried to use AntlrVSIX but it was agonizingly slow. This really saved the day for me.

**Comment by sharwell** [comment] 2021-01-11 15:26
Duplicate of tunnelvisionlabs/LangSvcV2#102

**Closed by sharwell** 2021-01-11 15:26 UTC

**Comment by sharwell** [comment] 2021-01-11 15:28
> In order to run this extension it is necessary to allow synchronous autoload of extensions as described in the article but it has some influence on performance

While it is possible for extensions to negatively impact performance when this configuration is enabled, such a condition was never observed or reported for this extension.
