### ISSUE TITLE
Unable to set Antlr4 Build Action in .Net Core 2 project in Visual Studio 2017

### ISSUE THREAD

**Issue by jaydeept** [tunnelvisionlabs/antlr4cs#249] opened 2017-10-02 14:45 UTC
I have created a .Net Core 2 project and wanted to add Grammar.g4 file. I have added Nuget packages called "ANtlr4", "Antlr4.Runtime" and "Antlr4.CodeGenerator" with latest available version 4.6.4. Somehow, I am not able to change "Build Action" to Antlr4 for my Grammar.g4 file. Because of that, it's not generating parser and lexer files. Can anyone please help here what's wrong going on?

**Comment by sharwell** [comment] 2017-10-02 14:54
Due to implementation differences in the new project system, the old methods for supporting this feature no longer work (see dotnet/project-system#113). However, I was able to add full support for this functionality (and more) in #234, which will be part of the next release.

:bulb: Note that you can still set this property by editing the project file manually. It is only the **Properties** window which has the problem.

:memo: While this is a duplicate of #193, keep in mind that a solution is on the way soon.

**Closed by sharwell** 2017-10-02 14:54 UTC

**Comment by GeorgDangl** [comment] 2017-10-02 15:26
For me, adding this to tmy `csproj` file is working well:

    <ItemGroup>
      <Antlr4 Include="Calculator.g4">
        <Generator>MSBuild:Compile</Generator>
        <CustomToolNamespace>Dangl.Calculator.Generated</CustomToolNamespace>
        <Listener>False</Listener>
        <Visitor>True</Visitor>
      </Antlr4>
    </ItemGroup>

**Comment by jaydeept** [comment] 2017-10-03 09:24
I did try to modify `csproj` file but still not generating lexer and parser file.
I am copying my `csproj` file here. Can anyone please spot what's wrong?

> <Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.0</TargetFramework>
    <AssemblyName>Pds.QueryLanguageGrammar</AssemblyName>
    <RootNamespace>Pds.QueryLanguageGrammar</RootNamespace>
	<DocumentationFile>..\..\build\doc\xml\Pds.QueryLanguageGrammar.xml</DocumentationFile>
    <OutputPath>..\..\build\$(Configuration)\Pds\</OutputPath>
    <BaseIntermediateOutputPath>..\..\work\$(MSBuildProjectName)\</BaseIntermediateOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Antlr4 Include="Grammar.g4">
      <Generator>MSBuild:Compile</Generator>
      <CustomToolNamespace>Pds.QueryLanguageGrammar</CustomToolNamespace>
      <Listener>True</Listener>
      <Visitor>False</Visitor>
    </Antlr4>
  </ItemGroup>
</Project>
